### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by q55x8x** [q55x8x/Peronality-Creator#1]
Add a way of saving settings such as last opened project

**Comment by png2** [comment]
This might be what I did

On my branch the program remembers the persona opened and the tabs opened

**Comment by q55x8x** [comment]
This is exactely what you did. But I normally do this a bit imo easier with a generic binary serializer. Using this we can keep typesafety in our settings files. But this can be considered at any time and needs so clear decision which road we go now.

**Comment by q55x8x** [comment]
Added my approach in the current mainFrm restructure branch

**Comment by png2** [comment]
It doesn't really matter for me as long as it works so I say we keep what we have
