### ISSUE TITLE
The tabs open in the wrong order

### ISSUE THREAD

**Issue by png2** [q55x8x/Peronality-Creator#12]
The last opened tab is on the left while it should be on the right for me...

Or allowing the user to choose

**Comment by q55x8x** [comment]
I think allowing the user to choosen would be the best bet here as i like them opening the newest left

**Comment by png2** [comment]
Indeed I just realized that visual studio opened them that way while most of the other editors add them to the right

**Comment by png2** [comment]
From what I saw on the component we can't control the order without changing it's code so we can close that one
