### ISSUE TITLE
Add a search on the treeview

### ISSUE THREAD

**Issue by png2** [q55x8x/Peronality-Creator#17]
Add a realtime search by folder/filename on the treeview

**Comment by q55x8x** [comment]
As I mentioned in #34 I think we should design an exntended TreeView Control. In there we could also include a textBox that "pops up" as soon as the user starts typing when the treeview is focussed and while the text changes we could live search through the nodes and filter them.

**Comment by q55x8x** [comment]
see 96476c4ac418bb5d6c518c67d7581cab8a609f7a and #39
