### ISSUE TITLE
Merging savePaths to master

### ISSUE THREAD

**Issue by q55x8x** [q55x8x/Peronality-Creator#21]
I just merged the mainFrm rewrite into master. To also include spell checking we could now try to merge savePaths too to get ready to push towards a kind of beta/alpha functional build.

**Comment by png2** [comment]
Merged the spellchecker, the save of the opened personas upon closing and the remove entry in the tree menu

It remains the save of the opened tabs, I wait our final decision upon the rewrite of the openFile to implement it

**Comment by png2** [comment]
I added the saving of the opened tabs and had to refactor the way the save/close was handled to separate them, Please check commit e4428bc10a4273138889a8bc4e7e839fd6b4839a
