### ISSUE TITLE
ctrl-click select destination or only jump?

### ISSUE THREAD

**Issue by q55x8x** [q55x8x/Peronality-Creator#22]
As the careet movement is fixed now I first highlighted the complete goto destination after jumping there. But it kinda looked nice. A problem could be that by directly typing after a jump there the input would overwrite the selection.
So the question is what would be wanted more selecting or just jumping to the end of the line?

**Comment by png2** [comment]
Personaly I found selecting the whole line easier to spot

And this feature is meant to quick traval not to edit the target line anyway, the modifications will most likely happen on the text below the target

I'm comiting with the while line selected we can change it later easily anyway

**Comment by q55x8x** [comment]
I think for a final decision we should wait for some user input.
But you made a good point and I agree to keep the changes (just made a little optimization ;) )
also because I think selecting just looks better.
