### ISSUE TITLE
master branch doesn't compile anymore

### ISSUE THREAD

**Issue by q55x8x** [q55x8x/Peronality-Creator#28]
I just pulled your changes and had to fix some assembly references.
But I am still getting a huge load of errors in the textBoxPlugin project. 
Some advice?

**Comment by png2** [comment]
Do you have the 3 spellchecker projects in the solution ?

If so you have to build them in the following order : i00BindingList, i00SpellChecker, FastColoredtextBoxPlugin

If you don't you hev to add the 3 projects that are in the Spellchecker directory as I missed something somewhere

**Comment by q55x8x** [comment]
~~binding list and spellcheck both compile I have all 3 projects added to the project and fixed the references. The only one not compiling is the textBox plugin.~~

### EDIT:

ok somehow i had to compile the re-add the spellcheck to the plugin project 
fixed now

**Comment by png2** [comment]
If I remember correctly at one point i had a conflict between the version of Fast Colored they used in the plugin and the one we used in the project

Try deleting the reference of fastcolored in the plugin and adding the one we use in the project

Sorry about that I'm not sure about what is commited or not concerning the project configuration

**Comment by q55x8x** [comment]
well since i got it working again i pushed the changes to the project if this brakes your project again we may have to investigate this and find a better way to manage them
