### ISSUE TITLE
Add Spell checking

### ISSUE THREAD

**Issue by png2** [q55x8x/Peronality-Creator#3]
This one seems compatible with the txt editor you are using : http://www.codeproject.com/Articles/265823/i-Spell-Check-and-Control-Extensions-No-Third-Pa

Otherwise : http://www.codeproject.com/Messages/4892605/Spell-Check.aspx

**Comment by png2** [comment]
A first version in in place in my branche. I probably pushed way too more things when I added the other projects as I have no idea what is needed and what should be ignored in a .Net project

**Comment by q55x8x** [comment]
Nice :)
I will try this out later.
Adding more projects as long as its done to the solution shouldnt be a problem as i used a gitignore for .NET projects provided by github themselfes but I'll have a look at it.

**Comment by q55x8x** [comment]
Just took a look at the spellchecker. looks really good _thumbsup_
