### ISSUE TITLE
When double clicking on a already opened tab it doesn't focus it

### ISSUE THREAD

**Issue by png2** [q55x8x/Peronality-Creator#30]
Well it should focus an opened tab id you try to reopen the file

**Comment by q55x8x** [comment]
we could also just loop trhough all tabs and compare the filepaths

**Comment by png2** [comment]
That's what i planned to do and did :)

**Comment by q55x8x** [comment]
have just seen the commit :D

**Comment by png2** [comment]
Well i thought you were sleeping so I started refactoring left and right :D

**Comment by q55x8x** [comment]
Well I think sleeping is what I'm gonna do next :D but wasn't really coding the last 2 hours so no problems. just quickly fixed the asterisk removal ;)
