### ISSUE TITLE
ctrl-click on vocab regex matching sometimes shows strange behaviour

### ISSUE THREAD

**Issue by q55x8x** [q55x8x/Peronality-Creator#40]
Basically ctrl-click on vocab works as added in 1de0cfef03bb217aa9f067b0f89bd76a1659bf3a.
But when there are multiple vocab uses in one line the matching always extracts the first occurrence. 
I tried to keep you this similar to your code as possible because your implementation just seemed good to go. And while debugging I found no error in there but haven't found any cause why there is always only 1 match with my code.

**Comment by png2** [comment]
If you did it like I did with @goto/chance it should work with the right occurrence as I had the same problem hence the rewrite. I'll take a look at it ASAP

Sorry I can't be of any help lately I tried to take a look at the tree search but I'm busy with people coming back from holidays and catching up. Also I'm having quite the hard time with playing with UI stuff in visual studio so I loose a lot of time compared to before where I just had to adapt your code

**Comment by q55x8x** [comment]
No problem I got a lot more busy then expected too lately. I am able to extract all Matches in the Line now so I should be able to change back to your approach and get it working now ;)

### EDIT:

works now ( 54045e85c8085d565fea184acaf43008512e54a7 )
