### ISSUE TITLE
Add ctl+click on #Vocab

### ISSUE THREAD

**Issue by png2** [q55x8x/Peronality-Creator#6]
When you ctl+click on a #Vocab tag in a file, it opens the corresponding vocab file in a new tab (or focus on the right tab if already opened)

Warning : some #Vocab are system and therefore do not have a file in /Vocabulary

**Comment by q55x8x** [comment]
Done in: 1de0cfef03bb217aa9f067b0f89bd76a1659bf3a and 54045e85c8085d565fea184acaf43008512e54a7
